
CREATE OR REPLACE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA RETAIL_DB.SALES_STAGE;

CREATE OR REPLACE FILE FORMAT RETAIL_DB.SALES_STAGE.csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ',' 
  SKIP_HEADER = 1
  NULL_IF = ('NULL','')
  TRIM_SPACE = TRUE;

  CREATE OR REPLACE STAGE RETAIL_DB.SALES_STAGE.azure_stage
  URL='azure://sfhexastorage.blob.core.windows.net/monthly-sales'
  FILE_FORMAT = RETAIL_DB.SALES_STAGE.csv_format
  CREDENTIALS=(AZURE_SAS_TOKEN='?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupyx&se=2025-10-23T17:42:04Z&st=2025-10-22T09:27:04Z&spr=https&sig=VGd6J9B4ffvNkdB8%2FgkH8mpLQ2Q9ac65xyg6RNNp4DI%3D');

CREATE OR REPLACE TABLE RETAIL_DB.SALES_STAGE.raw_sales (
  OrderID VARCHAR,
  OrderDate DATE,
  MonthOfSale VARCHAR,
  CustomerID VARCHAR,
  CustomerName VARCHAR,
  Country VARCHAR,
  Region VARCHAR,
  City VARCHAR,
  Category VARCHAR,
  Subcategory VARCHAR,
  Quantity NUMBER,
  Discount FLOAT,
  Sales FLOAT,
  Profit FLOAT
);


SELECT * FROM RAW_SALES;
-- Create database if not already created
CREATE DATABASE IF NOT EXISTS LOG_ANALYTICS;

-- Create schema CURATED
CREATE SCHEMA IF NOT EXISTS LOG_ANALYTICS.CURATED;

SELECT OrderID, COUNT(*) AS cnt
FROM CURATED.SALES_CLEANED
GROUP BY OrderID
HAVING COUNT(*) > 1;

SELECT  * FROM SALES_CLEANED;

