-- Create three warehouses for performance comparison
CREATE WAREHOUSE WH_SMALL  WITH WAREHOUSE_SIZE = 'SMALL'  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE WH_MEDIUM WITH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE WH_LARGE  WITH WAREHOUSE_SIZE = 'LARGE'  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE OR REPLACE TABLE LARGE_ORDERS AS
SELECT 
    SEQ8() AS ORDER_ID,
    RANDOM() * 1000 AS AMOUNT,
    DATEADD(day, UNIFORM(0, 1000, RANDOM()), TO_DATE('2020-01-01')) AS ORDER_DATE,
    UNIFORM(1, 5000, RANDOM()) AS CUSTOMER_ID
FROM TABLE(GENERATOR(ROWCOUNT => 10000000));

select * from LARGE_ORDERS;

ALTER WAREHOUSE WH_MEDIUM SET
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY = 'ECONOMY';

DROP WAREHOUSE IF EXISTS WH_SMALL;
DROP WAREHOUSE IF EXISTS WH_MEDIUM;
DROP WAREHOUSE IF EXISTS WH_LARGE;


