CREATE OR REPLACE DATABASE TRAINING_DB;
CREATE OR REPLACE SCHEMA TRAINING_DB.RAW;
CREATE OR REPLACE TABLE RAW.SALES (
    ID INT,
    CUSTOMER STRING,
    AMOUNT FLOAT,
    SALE_DATE DATE
);

insert into sales values (101, 'Tina', 34500, '2025-10-10');

select * from sales
select * from sales

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA tpch_sf1;

SHOW TABLES;


SELECT * FROM CUSTOMER LIMIT 10;


SELECT C_CUSTKEY,C_NAME,C_NATIONKEY
FROM CUSTOMER
WHERE C_NATIONKEY=14;


SELECT * FROM ORDERS;

SELECT C.C_NAME AS CUSTOMER_NAME,
O.O_ORDERKEY,
O.O_ORDERDATE,
O.O_TOTALPRICE
FROM CUSTOMER C
JOIN ORDERS O
ON C.C_CUSTKEY=O.O_CUSTKEY
LIMIT 20;



--AGGREGATION
SELECT C.C_NAME,
SUM(O.O_TOTALPRICE) AS TOTAL_SALES
FROM CUSTOMER C
JOIN ORDERS O
ON C.C_CUSTKEY=O.O_CUSTKEY
GROUP BY C.C_NAME
ORDER BY TOTAL_SALES DESC
lIMIT 15;

SELECT * FROM ORDERS;


SELECT O_ORDERKEY,O_ORDERDATE,O_TOTALPRICE
FROM ORDERS
WHERE YEAR(O_ORDERDATE) =1996
ORDER BY O_ORDERDATE
LIMIT 10;

SELECT * FROM REGION;
SELECT * FROM NATION;


SELECT R.R_NAME AS REGION,
ROUND(AVG(O.O_TOTALPRICE),2) AS AVG_ORDER_VALUE
FROM REGION R
JOIN NATION N ON R.R_REGIONKEY=N.N_REGIONKEY
JOIN CUSTOMER C ON N.N_NATIONKEY=C.C_NATIONKEY
JOIN ORDERS O ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY R.R_NAME
ORDER BY AVG_ORDER_VALUE DESC;


CREATE OR REPLACE DATABASE MY_PRACTICE_DB;
USE MY_PRACTICE_DB;
CREATE OR REPLACE TABLE MY_TOP_CUSTOMERS AS
SELECT C.C_NAME,SUM(O.O_TOTALPRICE) AS TOTAL_SALES
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS O
ON O.O_CUSTKEY=C.C_CUSTKEY
GROUP BY C.C_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 20;


SELECT * FROM MY_PRACTICE_DB.PUBLIC.MY_TOP_CUSTOMERS;

SELECT 
  o_orderstatus,
  AVG(o_totalprice) AS avg_totalprice
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.orders
GROUP BY o_orderstatus
ORDER BY avg_totalprice ASC;

SELECT 
  C_NAME,c_phone,c_nationkey
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.customer
order by c_nationkey asc, c_name asc
limit 15;

DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.orders;

SELECT o_custkey,o_orderdate,year(o_orderdate),month(o_orderdate) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.orders
ORDER BY o_orderdate DESC
limit 100;

SELECT COUNT(*) AS total_orders FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.orders;

SELECT 
    O_ORDERKEY, 
    COUNT(*) AS order_count
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.orders
GROUP BY O_ORDERKEY;

