create or replace database practice;
use database practice;

CREATE OR REPLACE SCHEMA practice.external_stage;

CREATE OR REPLACE STAGE practice.external_stage.aws_stage
URL = 's3://bucketsnowflakes3';

// List files in stage

LIST @practice.external_stage.aws_stage;
create or replace database our_first_db;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
  ORDER_ID     VARCHAR(30),
  AMOUNT       NUMBER(38,0),
  PROFIT       NUMBER(38,0),
  QUANTITY     NUMBER(38,0),
  CATEGORY     VARCHAR(30),
  SUBCATEGORY  VARCHAR(30)
);


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
  FROM @practice.external_stage.aws_stage
  FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1)
  PATTERN = '.*OrderDetails.*';

  SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS LIMIT 10;

  CREATE OR REPLACE TABLE ORDERS_CACHING (
  ORDER_ID     VARCHAR(30),
  AMOUNT       NUMBER(38,0),
  PROFIT       NUMBER(38,0),
  QUANTITY     NUMBER(38,0),
  CATEGORY     VARCHAR(30),
  SUBCATEGORY  VARCHAR(30),
  DATE         DATE
);

INSERT INTO ORDERS_CACHING 
SELECT
  t1.ORDER_ID,
  t1.AMOUNT,
  t1.PROFIT,
  t1.QUANTITY,
  t1.CATEGORY,
  t1.SUBCATEGORY,
  DATE_FROM_PARTS(1970,1,1) + (UNIFORM(15000,17000,RANDOM()))  -- generates random date
FROM ORDERS t1
CROSS JOIN (SELECT * FROM ORDERS) t2;

SELECT * FROM ORDERS_CACHING WHERE DATE = '2020-06-09';
DROP TABLE ORDERS_CACHING;

ALTER TABLE ORDERS_CACHING CLUSTER BY (DATE);

SELECT * FROM ORDERS_CACHING WHERE DATE = '2020-01-05';



SELECT * FROM ORDERS_CACHING WHERE MONTH(DATE)=11;

ALTER TABLE ORDERS_CACHING CLUSTER BY ( MONTH(DATE) );

