

//// Swapping tables

// Setting up dev table
CREATE TRANSIENT SCHEMA OUR_FIRST_DB.COPIED_SCHEMA
CLONE OUR_FIRST_DB.PUBLIC;

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.LANGUAGES;  //dev table
SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES//prod table


// Modifying "Dev Table"
DELETE FROM OUR_FIRST_DB.COPIED_SCHEMA.LANGUAGES WHERE LEVEL_SPOKEN = 'Basic';

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.LANGUAGES


// Swapping Tables
ALTER TABLE OUR_FIRST_DB.COPIED_SCHEMA.LANGUAGES
SWAP WITH OUR_FIRST_DB.PUBLIC.LANGUAGES

// Verifying results
SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.LANGUAGES; --
SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES;
