// Cloning

SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES;

show tables;
CREATE TABLE OUR_FIRST_DB.PUBLIC.LANGUAGES_CLONE
CLONE OUR_FIRST_DB.PUBLIC.LANGUAGES;


// Validate the data
SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES_CLONE;


// Update cloned table

UPDATE OUR_FIRST_DB.public.LANGUAGES_CLONE
SET LEVEL_SPOKEN = NULL;

SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES ;

SELECT * FROM OUR_FIRST_DB.PUBLIC.LANGUAGES_CLONE;


// Cloning a temporary table is not possible
CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TEMP_TABLE(
  id int);

CREATE TRANSIENT TABLE OUR_FIRST_DB.PUBLIC.TABLE_COPY
CLONE OUR_FIRST_DB.PUBLIC.TEMP_TABLE;

CREATE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TEMPTABLE_COPY
CLONE OUR_FIRST_DB.PUBLIC.TEMP_TABLE;
SELECT * FROM OUR_FIRST_DB.PUBLIC.TABLE_COPY;