
CREATE DATABASE LOG_ANALYTICS;
USE DATABASE LOG_ANALYTICS;
CREATE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE LOGS_CLEANED (
        EVENT STRING,
        USER_NAME STRING,
        TIMESTAMP STRING,
        EVENT_TIME TIMESTAMP_NTZ
    )

SELECT * FROM LOG_ANALYTICS.PUBLIC.LOGS_CLEANED;
