CREATE OR REPLACE STAGE azure_stage_sas
URL='azure://sfhexastorage.blob.core.windows.net/snowflakecontainer'
CREDENTIALS=(AZURE_SAS_TOKEN='?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupyx&se=2025-10-17T01:58:38Z&st=2025-10-16T17:43:38Z&spr=https&sig=6gdncAJVTEa%2FL7Ejg0HQqKdoi%2BJomxEnZMZsCqWzAO8%3D')
FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1);

CREATE OR REPLACE PIPE azure_pipe_sas
AS
COPY INTO PUBLIC.large_orders
FROM @azure_stage_sas
FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1)
ON_ERROR='SKIP_FILE';

CREATE OR REPLACE TABLE CUSTOMER_DATA(
  ID int,
  CUSTOMER STRING,
  REGION STRING,
  AMOUNT number(5,2),
  Loaded_At TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER PIPE azure_pipe_sas REFRESH;

SELECT * FROM TABLE CUSTOMER_DATA;



CREATE OR REPLACE TASK refresh_customer_pipe
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0/5 * * * * UTC'
AS
ALTER PIPE azure_pipe_sas REFRESH;


SELECT SYSTEM$PIPE_STATUS('AZURE_PIPE_SAS');


