CREATE DATABASE MIGRATION_DB;
USE SCHEMA MIGRATION_DB.PUBLIC;

CREATE OR REPLACE TABLE CUSTOMER (
    id INT,
    customer STRING,
    region STRING,
    amount NUMBER(10,2),
    load_date DATE
);

SELECT * FROM CUSTOMER;
